checks:
  php:
    code_rating: true
    duplication: true

build:
  environment:
    php:
      - 7.1
      - 7.2
      - 7.3

  tests:
    before:
      - "phpunit"

before_commands:
  - "composer install --no-interaction --prefer-source"